### ISSUE TITLE
nineth issue

### ISSUE THREAD

**Issue by 7flash** [buildship-dev/web3-login#9] opened 2022-06-15 06:28 UTC
![image](https://user-images.githubusercontent.com/4569866/173757087-b63b9d74-4f4b-4975-8422-303edf88d931.png)

Reproduce: https://gitpod.io/#github.com/7flash/web3-login-issue-nineth

**Comment by caffeinum** [comment] 2022-06-21 03:37
thanks! the problem is you have put `useWeb3` _outside_ of `Web3Provider`.

see example, I specifically created `AddressView` to overcome that:
https://github.com/buildship-dev/web3-login/blob/main/src/App.tsx

**Comment by caffeinum** [comment] 2022-06-21 03:39
<img width="455" alt="image" src="https://user-images.githubusercontent.com/1909384/174711249-a3184ab1-74cf-42df-b7cc-5b19adc258b6.png">
this fixes the problem, see demo:

https://3000-7flash-web3loginissueni-6jx4mhynpvt.ws-us47.gitpod.io/

**Comment by caffeinum** [comment] 2022-06-21 03:39
also I have added `AddressView` and created `ProfileView` in the PR, feel free to leave your feedback while it's not yet merged: #10

**Closed as completed by caffeinum** 2022-06-21 03:39 UTC
